name: Automation Test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  JAVA_VERSION: 21

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: gradle
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2
      
      - name: Enable Gradle Wrapper
        run: chmod +x gradlew
      
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

  api_test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable Gradle Wrapper
        run: chmod +x gradlew

      - name: Run API Tests
        run: ./gradlew runApiTest

  web_test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable Gradle Wrapper
        run: chmod +x gradlew
        
      - name: Run Web Tests
        run: ./gradlew runWebTest --no-daemon -q
      
      - name: Generate Allure Report
        if: always()
        run: ./gradlew allureReport
        
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report