name: Automation Test + Allure Report

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

env:
  JAVA_VERSION: 21

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      # 1. checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. setup java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: gradle

      # 3. install chrome (for selenium)
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2

      # 4. make gradlew executable
      - name: Setup Gradle
        run: chmod +x gradlew

      # 5. run API automation
      - name: Run API Test
        run: ./gradlew runApiTest

      # 6. run Web automation
      - name: Run Web Test
        run: ./gradlew runWebTest

      # 7. merge allure results
      - name: Merge Allure Results
        if: always()
        run: |
          mkdir -p build/allure-results
          cp -r build/allure-results/api/* build/allure-results/ || true
          cp -r build/allure-results/web/* build/allure-results/ || true

      # 8. generate report
      - name: Generate Allure Report
        if: always()
        run: ./gradlew allureReport

      # 9. upload report
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report


  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages